#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : 
Version  : 3.1.8
Release  : 23
URL      : ftp://ftp.gnu.org/gnu/src-highlite/source-highlight-3.1.8.tar.gz
Source0  : ftp://ftp.gnu.org/gnu/src-highlite/source-highlight-3.1.8.tar.gz
Summary  : syntax highlighting for source documents
Group    : Development/Tools
License  : GFDL-1.1 GPL-3.0 GPL-3.0+
BuildRequires : boost
BuildRequires : boost-dev
BuildRequires : flex
BuildRequires : go
Patch1: fix-testcase-boost1.54.patch

%description


%prep
%setup -q -n source-highlight-3.1.8
%patch1 -p1

%build
%configure --disable-static --with-boost-regex=boost_regex \
--with-bash-completion=/usr/share/bash-completion/completions
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
